name: Build tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-tests:
    name: ${{ matrix.config.name }} ${{ matrix.build_type }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "Windows MSVC", os: windows-latest, cc: "cl", cxx: "cl" }
          - { name: "Windows MinGW", os: windows-latest, cc: "gcc", cxx: "g++" }
          - { name: "Ubuntu GCC", os: ubuntu-latest, cc: "gcc", cxx: "g++" }
          - {
              name: "MacOS Clang",
              os: macos-latest,
              cc: "clang",
              cxx: "clang++",
            }
        build_type:
          - Debug
          - Release

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get install libgtk-3-dev

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.config.name }}-${{ matrix.build_type }}

      - name: build with cmake
        uses: lukka/run-cmake@v3
        with:
          cmakeListsTxtPath: "${{ github.workspace }}/tests/CMakeLists.txt"
          cmakeAppendedArgs: "-D CMAKE_BUILD_TYPE=${{ matrix.build_type }} -D CMAKE_C_COMPILER=${{ matrix.config.cc }} -D CMAKE_CXX_COMPILER=${{ matrix.config.cxx }} -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache"
          buildWithCMakeArgs: "--config ${{ matrix.build_type }}"
          buildDirectory: "${{ github.workspace }}/build"
          cmakeBuildType: ${{ matrix.build_type }}
